### ISSUE TITLE
[Bug]: Falha ao ativar o módulo

### ISSUE THREAD

**Issue by fabiofbra** [pagseguro/payment-magento#12]
### Dados de Contato

fguimaraes@gmail.com

### O que aconteceu?

Ao tentar autorizar o módulo no magento 2.4.3, retorna "Unable to get the code, try again. =("

Passo a passo:
1. Insiro no nome que aparecerá na fatura;
2. Escolho Produção
3. Clico no botão Autorizar...
4. O site do Pagseguro é carregado pedindo para autentiar. Faço isso com nossas credenciais.
5. Na tela seguinte aparece pedindo autorização para o Magento 2.4. Clico em Autorizar.
6. Retorna para a administração do Magento com a mensagem "Unable to get the code, try again. =("

Como resolver?

### Versão da Magento/Adobe

2.4.0 até 2.4.5 (Magento/Adobe >= 2.4.0 e < 2.4.5)

### Qual a versão do PHP?

PHP 7.4

### Existem logs relevantes sobre o problema?

```bash
nada
```

### Meu log não contém informações confidenciais

- [X] Não estou enviando dados que violem a privacidade do cliente ou da loja.

### Qual a gravidade do problema?

Não consegui configurar o modulo

**Comment by elisei** [comment]
Oi @fabiofbra 

Obrigado pelo report!

A versão 100.1.12 foi lançada ontem, você pode confirmar qual a versão que está usando por favor?

```bash
composer show pagbank/payment-magento --all
```

**Comment by fabiofbra** [comment]
Oi @elisei 

Eu fiz o download dos arquivos para o 2.4.3 ontem de noite (30 minutos antes de criar o bug), coloquei na pasta app/code...

**Comment by elisei** [comment]
@fabiofbra 

Você pode entrar em uma ligação?

**Comment by fabiofbra** [comment]
posso sim!

**Comment by elisei** [comment]
Te mandei o link da sala por email, lhe aguardo por lá! =)

**Comment by elisei** [comment]
Identificado problema na roda de admin, após orientação o problema foi resolvido!
