### ISSUE TITLE
[Bug]: Não é possível configurar o módulo

### ISSUE THREAD

**Issue by schossler** [pagseguro/payment-magento#18]
### Dados de Contato

schossler@gmail.com

### O que aconteceu?

Após instalar o módulo, ao acessar a página de configuração do mesmo (Loja >>> Configurações >>> Vendas >>> Formas de pagamento) nenhuma configuração é apresentada. O erro no log está abaixo. 

PS: tentei num servidor de testes com 2.4.6 e erro parece ser o mesmo.

### Versão da Magento/Adobe

2.4.0 até 2.4.5 (Magento/Adobe >= 2.4.0 e < 2.4.5)

### Qual a versão do PHP?

PHP 8.1

### Existem logs relevantes sobre o problema?

```bash
[2023-06-04T00:31:07.622917+00:00] main.CRITICAL: Class "PagBank\PaymentMagento\Model\Adminhtml\Source\PaymentGroup" does not exist [] []...

Next Magento\Framework\Exception\LocalizedException: Tipo de bloco inválido: PagBank\PaymentMagento\Model\Adminhtml\Source\PaymentGroup in /home/centralfila/public_html/vendor/magento/framework/View/Layout/Generator/Block.php:278...
```

### Meu log não contém informações confidenciais

- [X] Não estou enviando dados que violem a privacidade do cliente ou da loja.

### Qual a gravidade do problema?

Não consegui configurar o modulo

**Comment by elisei** [comment]
Olá @schossler, tudo bem?

André, pode me informar qual método de instalação usou? (composer ou upload manual)

O arquivo em questão está presente em todas as versões: 
2.4.6 - https://github.com/pagseguro/payment-magento/blob/100.2.18/Model/Adminhtml/Source/PaymentGroup.php
2.4.0-2.4.5 - https://github.com/pagseguro/payment-magento/blob/100.1.18/Model/Adminhtml/Source/PaymentGroup.php

Se fez a instalação pelo composer você irá encontra-lo em:
vendor/pagbank/paymentmagento/Model/Adminhtml/Source/PaymentGroup.php

Dependendo da configuração do seu de servidor, pode ser necessário fazer a limpeza de cache do php depois de ter feito a instalação. Em todo caso tente reiniciar seu php e caso o problema persista, entre em contato com os dados de acesso da máquina no email pagseguro@o2ti.com que realizamos a instalação para você.

**Comment by schossler** [comment]
@elisei a instalação foi via composer 

percebi que o caminho ficou diferente do Erro ...
/public_html/vendor/pagbank/**payment-magento**/Model/Adminhtml/Source

**Comment by elisei** [comment]
Sim o caminho aí é o correto, por tanto reiniciei o php, faça a compilação:
bin/Magento s:di:c

Se persistir o erro, por favor encaminhe os dados de acesso.

**Comment by schossler** [comment]
@elisei muito obrigado deu certo aqui no servidor de testes ... vou partir para o de produção.
