### ISSUE TITLE
[Bug]: Um erro no servidor impediu a sua compra de ser feita. Por favor, tente colocar o seu pedido novamente.

### ISSUE THREAD

**Issue by schossler** [pagseguro/payment-magento#19]
### Dados de Contato

schossler@gmail.com

### O que aconteceu?

@elisei 
Ao tentar finalizar o pedido está dando erro. 
main.CRITICAL: InvalidArgumentException: Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded in vendor/magento/framework/Serialize/Serializer/Json.php:26

percebi que esses produtos estavam com o caractere º no nome ... não sei se isso influencia, se consegue testar ? Nos teste que fiz foi justamente essa caractere especial que não deixou finalizar a compra, após alterar o produto a compra ocorreu com sucesso.

### Versão da Magento/Adobe

2.4.0 até 2.4.5 (Magento/Adobe >= 2.4.0 e < 2.4.5)

### Qual a versão do PHP?

PHP 8.1

### Meu log não contém informações confidenciais

- [X] Não estou enviando dados que violem a privacidade do cliente ou da loja.

### Qual a gravidade do problema?

Nenhum cliente pode fazer um pagamento

**Comment by elisei** [comment]
Olá @schossler 

Realizei 2 testes com o caracter especial e não houve nenhum problema.
<details>
<summary>
<i>Teste com cartão</i>
</summary>

[2023-06-26T16:48:21.528643+00:00] main.DEBUG: array (
  'url' => 'https://sandbox.api.pagseguro.com/orders',
  'header' => '****',
  'payload' => '{"metadata":[{"store_id":1}],"reference_id":"000000631","description":"Pagamento do pedido #000000631","amount":{"value":46355,"currency":"BRL"},"customer":{"name":"Bruno Elisei","email":"*** protected ***","tax_id":"*** protected ***","phones":[{"country":55,"area":34,"number":"*** protected ***","type":"MOBILE"}],"address":{"postal_code":"38017190","street":"Doutor Jesu\\u00edno Felic\\u00edssimo","number":"*** protected ***","locality":"730","complement":"Boa Vista","city":"Uberaba","region":"Minas Gerais","region_code":"MG","country":"BRA"}},"items":[{"reference_id":"123","name":"dasdas 12\\u00ba ","quantity":1,"unit_amount":43300}],"shipping":{"address":{"postal_code":"38017190","street":"Doutor Jesu\\u00edno Felic\\u00edssimo","number":"*** protected ***","locality":"730","complement":"Boa Vista","city":"Uberaba","region":"Minas Gerais","region_code":"MG","country":"BRA"}},"notification_urls":["https:\\/\\/v246-pagseguro.magento.local\\/pagbank\\/notification\\/all\\/"],"charges":[{"amount":{"value":46355,"currency":"BRL"},"payment_method":{"type":"CREDIT_CARD","soft_descriptor":"DemoLocal","capture":true,"installments":"1","card":{"encrypted":"Sim8ML9JeLwYSewpIgLRjvheKkCv4AqTNZsR\\/blpU0ZT5uQR5K7vPrUCkzAu1NmoeJCfPsdQVJqww5l9bIMl5trUuYKhO\\/NbSHbV2B2Hpra1wXj5ZosWEhdjPCjt\\/TptF0Qb\\/Lcml3FIbxyvwuk+eqlFPTl1vnOA1qXNfuyaz\\/MsRUruohgc19dBpW5lN30bm07VgvPg1ArpdLF95+UsadsRaMdCrDF0W5N5FOQC99NvVUKSuDqPx\\/otX38KiXh9IwwhMHstAClTlG7POoNrErAY0zy6hCKhkh5WpqwDF7XyXQlizwWyHWyZGVohfKH5c+3+xmj1van+lZsF6e22Tw==","store":true}},"splits":{"method":"FIXED","receivers":[{"account":{"id":"ACCO_A54FD6CD-E43F-4783-A7F4-E4352285DC87"},"amount":{"value":12990}},{"account":{"id":"ACCO_1C7377DF-5D98-43E0-BDF6-FA6591316595"},"amount":{"value":33365}}]}}]}',
  'response' => '{"id":"ORDE_69A52627-4AA9-442E-9850-6CA19E494715","reference_id":"000000631","created_at":"2023-06-26T13:48:16.396-03:00","customer":{"name":"Bruno Elisei","email":"*** protected ***","tax_id":"*** protected ***","phones":[{"type":"MOBILE","country":"55","area":"34","number":"*** protected ***"}]},"items":[{"reference_id":"123","name":"dasdas 12\\u00ba ","quantity":1,"unit_amount":43300}],"shipping":{"address":{"street":"Doutor Jesu\\u00edno Felic\\u00edssimo","number":"*** protected ***","complement":"Boa Vista","locality":"730","city":"Uberaba","region_code":"MG","country":"BRA","postal_code":"38017190"}},"charges":[{"id":"CHAR_4FCF5937-3732-4840-A378-28EC312EC059","status":"PAID","created_at":"2023-06-26T13:48:16.888-03:00","paid_at":"2023-06-26T13:48:20.000-03:00","description":"","amount":{"value":46355,"currency":"BRL","summary":{"total":46355,"paid":46355,"refunded":0}},"payment_response":{"code":"20000","message":"SUCESSO","reference":"032416400102"},"payment_method":{"type":"CREDIT_CARD","installments":1,"capture":true,"card":{"id":"CARD_0F246300-8B50-44A4-9A76-8B44D6A2F1E6","brand":"visa","first_digits":"474747","last_digits":"4747","exp_month":"6","exp_year":"2025","holder":{"name":"dsd sdsd"},"store":true},"soft_descriptor":"DemoLocal"},"links":[{"rel":"SELF","href":"https:\\/\\/sandbox.api.pagseguro.com\\/charges\\/CHAR_4FCF5937-3732-4840-A378-28EC312EC059","media":"application\\/json","type":"GET"},{"rel":"CHARGE.CANCEL","href":"https:\\/\\/sandbox.api.pagseguro.com\\/charges\\/CHAR_4FCF5937-3732-4840-A378-28EC312EC059\\/cancel","media":"application\\/json","type":"POST"},{"rel":"SPLIT","href":"https:\\/\\/sandbox.api.pagseguro.com\\/splits\\/SPLI_EE7096B1-BCA3-4686-8719-C43258D05B63","media":"application\\/json","type":"GET"}]}],"notification_urls":["https:\\/\\/v246-pagseguro.magento.local\\/pagbank\\/notification\\/all\\/"],"links":[{"rel":"SELF","href":"https:\\/\\/sandbox.api.pagseguro.com\\/orders\\/ORDE_69A52627-4AA9-442E-9850-6CA19E494715","media":"application\\/json","type":"GET"},{"rel":"PAY","href":"https:\\/\\/sandbox.api.pagseguro.com\\/orders\\/ORDE_69A52627-4AA9-442E-9850-6CA19E494715\\/pay","media":"application\\/json","type":"POST"}]}',
  'error_msg' => NULL,
) [] []
</details>

<details>
<summary>
<i>Teste com Boleto</i>
</summary>
[2023-06-26T16:47:33.661373+00:00] main.DEBUG: array (
  'url' => 'https://sandbox.api.pagseguro.com/orders',
  'header' => '****',
  'payload' => '{"metadata":[{"store_id":1}],"reference_id":"000000630","description":"Pagamento do pedido #000000630","amount":{"value":43855,"currency":"BRL"},"customer":{"name":"Bruno Elisei","email":"*** protected ***","tax_id":"*** protected ***","phones":[{"country":55,"area":34,"number":"*** protected ***","type":"MOBILE"}],"address":{"postal_code":"38017190","street":"Doutor Jesu\\u00edno Felic\\u00edssimo","number":"*** protected ***","locality":"730","complement":"Boa Vista","city":"Uberaba","region":"Minas Gerais","region_code":"MG","country":"BRA"}},"items":[{"reference_id":"123","name":"dasdas 12\\u00ba ","quantity":1,"unit_amount":43300}],"shipping":{"address":{"postal_code":"38017190","street":"Doutor Jesu\\u00edno Felic\\u00edssimo","number":"*** protected ***","locality":"730","complement":"Boa Vista","city":"Uberaba","region":"Minas Gerais","region_code":"MG","country":"BRA"}},"notification_urls":["https:\\/\\/v246-pagseguro.magento.local\\/pagbank\\/notification\\/all\\/"],"charges":[{"amount":{"value":43855,"currency":"BRL"},"payment_method":{"type":"BOLETO","boleto":{"due_date":"2023-07-01","instruction_lines":{"line_1":"N\\u00e3o receber ap\\u00f3s vencimento."},"holder":{"name":"Bruno Elisei","email":"*** protected ***","tax_id":"*** protected ***","address":{"postal_code":"38017190","street":"Doutor Jesu\\u00edno Felic\\u00edssimo","number":"*** protected ***","locality":"730","complement":"Boa Vista","city":"Uberaba","region":"Minas Gerais","region_code":"MG","country":"BR"}}}},"splits":{"method":"FIXED","receivers":[{"account":{"id":"ACCO_A54FD6CD-E43F-4783-A7F4-E4352285DC87"},"amount":{"value":13545}},{"account":{"id":"ACCO_1C7377DF-5D98-43E0-BDF6-FA6591316595"},"amount":{"value":30310}}]}}]}',
  'response' => '{"id":"ORDE_FDEA26BD-3E5A-457A-A34D-B38F10E426DA","reference_id":"000000630","created_at":"2023-06-26T13:47:30.594-03:00","customer":{"name":"Bruno Elisei","email":"*** protected ***","tax_id":"*** protected ***","phones":[{"type":"MOBILE","country":"55","area":"34","number":"*** protected ***"}]},"items":[{"reference_id":"123","name":"dasdas 12\\u00ba ","quantity":1,"unit_amount":43300}],"shipping":{"address":{"street":"Doutor Jesu\\u00edno Felic\\u00edssimo","number":"*** protected ***","complement":"Boa Vista","locality":"730","city":"Uberaba","region_code":"MG","country":"BRA","postal_code":"38017190"}},"charges":[{"id":"CHAR_CC0085F6-6EB9-408A-AE98-77AE2D65CD32","status":"WAITING","created_at":"2023-06-26T13:47:30.784-03:00","description":"","amount":{"value":43855,"currency":"BRL","summary":{"total":43855,"paid":0,"refunded":0}},"payment_response":{"code":"20000","message":"SUCESSO"},"payment_method":{"type":"BOLETO","boleto":{"id":"8E7D2DCF-B491-4A51-B8B0-0AA823271053","barcode":"03399853012970000024227020901016278150000015630","formatted_barcode":"03399.85301 29700.000242 27020.901016 2 78150000015630","due_date":"2023-07-01","instruction_lines":{"line_1":"N\\u00e3o receber ap\\u00f3s vencimento."},"holder":{"name":"Bruno Elisei","tax_id":"*** protected ***","email":"*** protected ***","address":{"region":"Minas Gerais","city":"Uberaba","postal_code":"38017190","street":"Doutor Jesu\\u00edno Felic\\u00edssimo","number":"*** protected ***","locality":"730","country":"BR","region_code":"MG"}}}},"links":[{"rel":"SELF","href":"https:\\/\\/boleto.sandbox.pagseguro.com.br\\/8e7d2dcf-b491-4a51-b8b0-0aa823271053.pdf","media":"application\\/pdf","type":"GET"},{"rel":"SELF","href":"https:\\/\\/boleto.sandbox.pagseguro.com.br\\/8e7d2dcf-b491-4a51-b8b0-0aa823271053.png","media":"image\\/png","type":"GET"},{"rel":"SELF","href":"https:\\/\\/sandbox.api.pagseguro.com\\/charges\\/CHAR_CC0085F6-6EB9-408A-AE98-77AE2D65CD32","media":"application\\/json","type":"GET"},{"rel":"SPLIT","href":"https:\\/\\/sandbox.api.pagseguro.com\\/splits\\/SPLI_A6ECC5CD-32B5-4CE0-B9A2-D52388FEC095","media":"application\\/json","type":"GET"}]}],"notification_urls":["https:\\/\\/v246-pagseguro.magento.local\\/pagbank\\/notification\\/all\\/"],"links":[{"rel":"SELF","href":"https:\\/\\/sandbox.api.pagseguro.com\\/orders\\/ORDE_FDEA26BD-3E5A-457A-A34D-B38F10E426DA","media":"application\\/json","type":"GET"},{"rel":"PAY","href":"https:\\/\\/sandbox.api.pagseguro.com\\/orders\\/ORDE_FDEA26BD-3E5A-457A-A34D-B38F10E426DA\\/pay","media":"application\\/json","type":"POST"}]}',
  'error_msg' => NULL,
) [] []
</details>

Por favor,  [ligue temporariamente o log do módulo](https://github.com/pagseguro/payment-magento/wiki/05---D%C3%BAvidas-Comuns-&-Pr%C3%A9-Requisitos#como-identificar-motivos-de-erros-de-pagamento) o do módulo e refaça a transação, assim conseguimos coletar o erro.

**Comment by schossler** [comment]
Bruno o arquivo de LOG payment.log não foi gerado ao tentar realizar a compra.

**Comment by elisei** [comment]
@schossler por gentileza, tente indicar um passo a passo no seu site de como reproduzir o erro.

**Comment by schossler** [comment]
Quando tento comprar esse produto dá o erro.
https://centralnumismatica.com.br/mexico-20-pesos-2017-fc-100-aniversario-constituic-o-do-mexico-1687793096-1687797658-1687798652.html

**Comment by elisei** [comment]
@schossler Lancei uma correção para o limite de caracteres enviados ao PagBank, por favor atualize e teste novamente.

**Comment by schossler** [comment]
@elisei mesmo erro ... 
main.CRITICAL: InvalidArgumentException: Unable to serialize value. Error: Malformed UTF-8 characters, possibly incorrectly encoded in /home/cnumis/public_html/vendor/magento/framework/Serialize/Serializer/Json.php:26

**Comment by elisei** [comment]
Olá @schossler 

Se você fez a atualização do módulo e limpou o cache do php passa a ser um problema local, nesse caso é necessário o envio de dados para pagbank@o2ti.com

**Comment by schossler** [comment]
@elisei restartei o apache e agora deu certo!
Muito Obrigado

**Comment by schossler** [comment]
Bom dia @elisei o problema voltou a ocorrer na peça com link abaixo. Detalhe que vendi várias outras com o caractere º, então deduzo realmente não ser ele. E não sei o que pode ser ... Caso necessário te envio dados por email.
https://centralnumismatica.com.br/russia-2-rublos-2012-200-aniversario-da-vitoria-1687744816.html

**Comment by elisei** [comment]
@schossler 
a versão 100.2.21 corrige o problema!
