### ISSUE TITLE
[Bug]: Erro ao gerar boleto

### ISSUE THREAD

**Issue by giovannicocco** [pagseguro/payment-magento#24]
### Dados de Contato

giovanni.coco@gmail.com

### O que aconteceu?

O método de pagamento por Boleto está com erro.

![WhatsApp Image 2023-07-25 at 10 53 37](https://github.com/pagseguro/payment-magento/assets/6585496/7a931059-72cf-4aa4-83ff-e48021ce3911)

### Método de Instalação

Via Composer

### Versão da Magento/Adobe

2.4.0 até 2.4.5 (Magento/Adobe >= 2.4.0 e < 2.4.5)

### Qual a versão do PHP?

PHP 7.4

### Meu log não contém informações confidenciais

- [X] Não estou enviando dados que violem a privacidade do cliente ou da loja.

### Qual a gravidade do problema?

Um dos métodos de pagamento não está funcionando

**Comment by elisei** [comment]
Olá @giovannicocco,

Preciso que [habilite o log](https://github.com/pagseguro/payment-magento/wiki/05---D%C3%BAvidas-Comuns-&-Pr%C3%A9-Requisitos#como-identificar-motivos-de-erros-de-pagamento), e me encaminhe. Mas sem analisar sugiro verificar já o relacionamento do [atributo cpf](https://github.com/pagseguro/payment-magento/wiki/05---D%C3%BAvidas-Comuns-&-Pr%C3%A9-Requisitos#gerenciamento-da-informa%C3%A7%C3%B5es-do-cliente) pois geralmente esse é o problema do erro 40002, mas com o log lhe dou orientação mais precisa.

**Comment by giovannicocco** [comment]
@elisei veja os últimos logs

[2023-07-25 14:20:33] main.DEBUG: array (
  'url' => 'https://api.pagseguro.com/orders',
  'header' => '****',
  'payload' => '{"metadata":[{"store_id":1}],"reference_id":"000000765","description":"Pagamento do pedido #000000765","amount":{"value":100,"currency":"BRL"},"customer":{"name":"Giovanni Co$
  'response' => '{"error_messages":[{"code":"40002","description":"invalid_parameter","parameter_name":"charges[0].payment_method.boleto.holder.email"}]}',
  'error_msg' => NULL,
) [] []

[2023-07-25 14:21:34] main.DEBUG: array (
  'url' => 'https://api.pagseguro.com/orders',
  'header' => '****',
  'payload' => '{"metadata":[{"store_id":1}],"reference_id":"000000766","description":"Pagamento do pedido #000000766","amount":{"value":100,"currency":"BRL"},"customer":{"name":"Giovanni Co$
  'response' => '{"error_messages":[{"code":"40002","description":"invalid_parameter","parameter_name":"charges[0].payment_method.boleto.holder.email"}]}',
  'error_msg' => NULL,
) [] []

[2023-07-25 14:22:18] main.DEBUG: array (
  'url' => 'https://api.pagseguro.com/orders',
  'header' => '****',
  'payload' => '{"metadata":[{"store_id":1}],"reference_id":"000000767","description":"Pagamento do pedido #000000767","amount":{"value":100,"currency":"BRL"},"customer":{"name":"Giovanni Co$
  'response' => '{"error_messages":[{"code":"40002","description":"invalid_parameter","parameter_name":"charges[0].payment_method.boleto.holder.email"}]}',
  'error_msg' => NULL,
) [] []

**Comment by elisei** [comment]
Oi @giovannicocco  o log tá cortado =(

Mas em teoria a Pags está indicando que o email está inválido, você pode me detalhar o fluxo seu de venda?

- É uma venda como cliente anônimo? 
- O email tem algum caracter inválido?
- Com outro usuário você consegue finalizar?

**Comment by giovannicocco** [comment]
@elisei atualizei o log! Vou checar o email

**Comment by giovannicocco** [comment]
@elisei realmente era o email eu estava usando um alias no Gmail giovanni.coco+cliente@gmail.com e o sinal de + causou o problema.

**Comment by elisei** [comment]
Boa @giovannicocco,

Posso fechar o ticket então?
