### ISSUE TITLE
[Bug]: Bug ao Abrir Mini Carrinho - Renderização das informações - Require_JS

### ISSUE THREAD

**Issue by Cyber-Root0** [pagseguro/payment-magento#25]
### Contact details

bruno@isoftsolutions.com.br

### What happened?

**Erro ao renderizar as informações do Mini Carrinho, observe que é apresentado um erro no Javascript após a instalação do Módulo. Estamos utilizando a versão 2.4.6 do Magento, fiz algumas validações internas e tudo indica que é no require-js do módulo:**

```
config: {
        mixins: {
            'mage/validation': {
                'PagBank_PaymentMagento/js/validation/custom-validation': true
            }
        }
    }
```
    
![Fix_27-07-PagSeguro](https://github.com/pagseguro/payment-magento/assets/70926805/ead97209-9952-41d2-a41c-25062d5aa23d)

    Quando o eu atribuo o valor "false" para a flag, compilo, e faço todo o procedimento de Deploy novamente, as informações do carrinho são renderizadas perfeitamente. Grato!

### Magento version

2.4.x (Magento >= 2.4.0)

### What version of php?

PHP 8.1

### My log does not contain confidential information

- [X] I am not sending data that violates the privacy of the customer or the store.

### What is the severity of the problem?

The store was offline, I could not configure the module

**Comment by elisei** [comment]
Olá @Cyber-Root0 

Eu tentei reproduzir o erro em um Magento 2.4.6-p1, além disso já testamos no 2.3.

Esse não me parece ser um conflito global, nesse caso é preciso que analise na construção de sua template a origem do problema, caso queira e tenha um ambiente de teste você pode encaminhar os dados de acesso para pagseguro@o2ti.com que ajudamos nessa análise. 

Segue o video do teste:

[Screencast_28_07_2023_09:05:52.webm](https://github.com/pagseguro/payment-magento/assets/1786389/568b1188-bce7-4c70-945b-3267d86751db)

**Comment by elisei** [comment]
Olá @Cyber-Root0 conseguiu analisar, podemos fechar o issue?

**Comment by Cyber-Root0** [comment]
@elisei Boa tarde! Desculpe a demora em responder, realizei alguns testes em nosso ambiente e era um módulo que estava dando conflito. "Amasty_SocialLogin" e o  "Amasty_SocialLoginLite".

Obrigado por toda a ajuda.
Abraços!
