### ISSUE TITLE
[Bug]: Validação de CPF no Checkout

### ISSUE THREAD

**Issue by Cyber-Root0** [pagseguro/payment-magento#27]
### Contact details

bruno@isoftsolutions.com.br

### What happened?

Olá, pensei que havia corrigido o problema,

Mas quando abri o Checkout Apresentou o seguinte erro na hora de validar o CPF.

Se puder verificar, por favor.

![image](https://github.com/pagseguro/payment-magento/assets/70926805/0d690690-8d2c-419f-a205-83fa8e14f7bd)

### Magento version

2.4.x (Magento >= 2.4.0)

### What version of php?

PHP 8.1

### Are there relevant logs about the problem?

```bash
Uncaught TypeError: Cannot read properties of undefined (reading 'call').  Exception occurred when checking element pagbank_paymentmagento_pix-payer-tax-id, check the 'pagbank-validate-tax-id' method.
    at $.validator.check (jquery.validate.min.js:62:107)
    at $.validator.checkForm (jquery.validate.min.js:41:163)
    at $.validator.form (jquery.validate.min.js:40:657)
    at jQuery.fn.init.valid (jquery.validate.min.js:22:115)
    at UiClass.beforePlaceOrder (pix.min.js:1:1033)
    at HTMLButtonElement.<anonymous> (knockout.min.js:391:164)
    at HTMLButtonElement.dispatch (jquery.min.js:348:476)
    at elemData.handle (jquery.min.js:334:166)
```

### My log does not contain confidential information

- [X] I am not sending data that violates the privacy of the customer or the store.

### What is the severity of the problem?

One of the payment methods is not working

**Comment by elisei** [comment]
Oi @Cyber-Root0 tudo bem?

Então a questão aqui é a mesma da Issue anterior sua, eu não sou capaz em um magento limpo reproduzir esse problema, somente com acesso a esse ambiente de vocês é que posso buscar alguma solução!

**Comment by schossler** [comment]
> Oi @Cyber-Root0 tudo bem?
> 
> Então a questão aqui é a mesma da Issue anterior sua, eu não sou capaz em um magento limpo reproduzir esse problema, somente com acesso a esse ambiente de vocês é que posso buscar alguma solução!

@elisei
Utilizar a configuração de Captura dos dados do Pagador ao finalizar o pedido não resolveria o problema ?
![image](https://github.com/pagseguro/payment-magento/assets/1133840/5b23aae2-2975-4234-8302-9936d2d868a3)

**Comment by elisei** [comment]
Olá @schossler é um possibilidade mas a causa raiz seguirá... então ideal é identificar e resolver!

**Comment by schossler** [comment]
@elisei 
quando o sistema identificar a falta ou erro destes campo o meio de pagamento poderia solicitar sozinho essas informações ... 
até para loja não perder a possível venda ... 

outra que ao utilizar o CPF ou telefone no meio de pagamento poderia atualizar na base para próxima compra não solicitar novamente ...

**Comment by elisei** [comment]
olá @schossler 

A primeira etapa ela já faz.

A segunda não acho adequado implementar!

**Comment by Cyber-Root0** [comment]
@elisei Nós identificamos que estava com um conflito com um dos temas que utilizamos.

Especificamente o tema da Amasty, "Jet Theme Pro".

Vamos corrigir internamente fazendo adaptações no tema, obrigado mais uma vez!

**Comment by elisei** [comment]
@Cyber-Root0 posso fechar o issue?
