### ISSUE TITLE
Não foi possível obter o código, tente novamente. =(

### ISSUE THREAD

**Issue by pfgianoto** [pagseguro/payment-magento#28]
### Dados de Contato

pfgianoto@gmail.com

### O que aconteceu?

Após realizar a instalação do módulo (usando Magento 2.4.1) na parte inicial das configurações após definir o nome da loja e escolher o ambiente e salvar, cliquei no botão para autorizar aonde fui levado para a conta do pagseguro pedindo permissão para autorizar a aplicação https://prnt.sc/eIh7eyx_d1sh após autorizar sou redirecionado de volta a tela de configuração da loja mas o seguinte erro aparece Não foi possível obter o código, tente novamente. =( https://prnt.sc/yRClEjkeFwVV

O que pode estar acontecendo?

### Método de Instalação

Via upload de arquivs (app/code)

### Versão da Magento/Adobe

2.4.0 até 2.4.5 (Magento/Adobe >= 2.4.0 e < 2.4.5)

### Qual a versão do PHP?

PHP 7.4

### Existem logs relevantes sobre o problema?

```bash
Os logs da loja estão ativos mas não foi gerado log.
```

### Meu log não contém informações confidenciais

- [X] Não estou enviando dados que violem a privacidade do cliente ou da loja.

### Qual a gravidade do problema?

Não consegui configurar o modulo

**Comment by elisei** [comment]
Olá @pfgianoto!

Por motivos de segurança rodas administrativas definidas como 'admin' não permitem a conexão, [por favor altere a roda do seu painel administrativo](https://magento.stackexchange.com/questions/113747/how-to-change-magento2-admin-url) e tente novamente.

**Comment by pfgianoto** [comment]
Deu certo @elisei Obrigado pelo rápido retorno e solução!
