### ISSUE TITLE
[Bug]: PR#22 productName com caracteres especiais 

### ISSUE THREAD

**Issue by schossler** [pagseguro/payment-magento#29]
### Dados de Contato

schossler@gmail.com

### O que aconteceu?

PR #22 trouxe de volta o problema com nome de produto com caractere especial como º ou ª (talvez alguns outros)  ao finalizar pedido.

### Método de Instalação

Via Composer

### Versão da Magento/Adobe

2.4.0 até 2.4.5 (Magento/Adobe >= 2.4.0 e < 2.4.5)

### Qual a versão do PHP?

PHP 8.1

### Existem logs relevantes sobre o problema?

```bash
não gera LOG
```

### Meu log não contém informações confidenciais

- [X] Não estou enviando dados que violem a privacidade do cliente ou da loja.

### Qual a gravidade do problema?

Não consegui configurar o modulo

**Comment by schossler** [comment]
@elisei continuo com problema em alguns produtos específicos exemplo: 
Brasil 500 Réis 1922 FC - 100º Aniversário - Independência do Brasil

Módulo está atualizado.

**Comment by elisei** [comment]
@schossler  Fixado na versão mais recente, por favor avalie.
