### ISSUE TITLE
[Dúvida]: Produtos retornando ao estoque

### ISSUE THREAD

**Issue by schossler** [pagseguro/payment-magento#38]
### Dados de Contato

schossler@gmail.com

### O que aconteceu?

Uso na minha configuração de boletos dias de vencimento = 3
Por enquanto percebi que boletos onde o pagamento é compensado somente 4 dias após os produtos voltam ao estoque. 
Fazendo com que eu tenha falhas no meu estoque.

No histórico de transações aparece assim.
    20 de out. de 2023 13:50:31 Pending Cliente Notificado
    20 de out. de 2023 13:50:32 Pending
    24 de out. de 2023 05:22:05 Processing
    24 de out. de 2023 05:22:05 Processing
    24 de out. de 2023 05:22:05 Processing
    24 de out. de 2023 05:22:05 Fatura #000003770 criada Cliente Notificado

E quando fui verificar as peças estavam de volta no site para vender.

### Método de Instalação

Via Composer

### Versão da Magento/Adobe

2.4.6+ (Magento/Adobe >= 2.4.6)

### Qual a versão do PHP?

PHP 8.1

### Meu log não contém informações confidenciais

- [X] Não estou enviando dados que violem a privacidade do cliente ou da loja.

### Qual a gravidade do problema?

Um dos métodos de pagamento não está funcionando

**Comment by elisei** [comment]
@schossler 

O período de baixa bancária é de até 3 dias úteis. Por isso o prazo de vencimento é diferente do prazo de cancelamento.
