### ISSUE TITLE
[Bug]: Pedidos Closed

### ISSUE THREAD

**Issue by schossler** [pagseguro/payment-magento#44]
### O que aconteceu?

Módulo está gerando Notificações conforme imagem abaixo em pedidos que foram reembolsados e status Closed.

![image](https://github.com/pagseguro/payment-magento/assets/1133840/78a1b093-b698-4836-b407-9b9d2cc5b5b5)

@elisei o módulo está funcionando a contento, muito obrigado pelo sempre pronto atendimento.

### Método de Instalação

Via Composer

### Versão da Magento/Adobe

2.4.6+ (Magento/Adobe >= 2.4.6)

### Qual a versão do PHP?

PHP 8.1

### Meu log não contém informações confidenciais

- [X] Não estou enviando dados que violem a privacidade do cliente ou da loja.

### Qual a gravidade do problema?

Não consegui configurar o modulo

**Comment by elisei** [comment]
Oi @schossler 

Eu tentei reproduzir esse erro aqui mas não tive sucesso, você tem certeza que state (não status) do pedido é realmente closed?

Conseguiria consultar o pedido via API para verificar?
![image](https://github.com/pagseguro/payment-magento/assets/1786389/aeb6a418-f8cb-433c-9091-a433a057e14f)

**Comment by schossler** [comment]
Não consigo consultar via API.

Realmente há diferenças ...
![image](https://github.com/pagseguro/payment-magento/assets/1133840/bed59e50-b296-4f5c-957b-8d0084199fed)

e a situação está 
 
![image](https://github.com/pagseguro/payment-magento/assets/1133840/d64b10e6-89fd-4d7a-b522-9c66ccfdb980)


ao mandar verificar a ordem pelo shell
![image](https://github.com/pagseguro/payment-magento/assets/1133840/758b7270-1f13-4005-b13d-a3fc10ee1b6a)

**Comment by elisei** [comment]
@schossler entendi

É possivelmente um erro no fluxo do memorando de crédito anterior, você precisa atualizar esse pedido via banco de dados!

**Comment by schossler** [comment]
Perfeito, farei isso, muito obrigado novamente.

**Comment by schossler** [comment]
Resolvido. 
Obrigado @elisei
