### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by Cairo-Maranzatto** [pagseguro/payment-magento#46]
### Dados de Contato

cairomaranzatto.jau@gmail.com

### Qual a sua dúvida?

Como eu configuro o módulo de pagamento do pagseguro no magento 2 para realizar venda recorrente (ou assinatura) por cartão de crédito?

### Versão da Magento/Adobe

2.3.x (Magento/Adobe >= 2.3.0 e < 2.4.0)

**Comment by elisei** [comment]
Olá @Cairo-Maranzatto,

A recorrência de pagamento, por não ser um processo nativo, precisa se apoiar em desenvolvimentos extras.

O primeiro ponto é no processo de pagamento adicionar uma flag para indicar se aquele pedido é ou não recorrente e, em solicitações futuras, se aquele é um pagamento sequencial.

Esse módulo cria essa flag:
https://github.com/elisei/pagbank-flag-recurring-magento

Mas a população do valor da flag depende do seu desenvolvimento.

Já o passo seguinte é a realização das cobranças. Aqui há várias abordagens possíveis; no módulo citado, há abordagem via API Rest do novo ciclo.

**Comment by elisei** [comment]
@Cairo-Maranzatto 

Estou encerrando esse issue, se ainda precisar de alguma informação por favor reabra.
