### ISSUE TITLE
Unable to get the code

### ISSUE THREAD

**Issue by ch31z3r83** [pagseguro/payment-magento#50]
### Dados de Contato

cheizer@gmail.com

### O que aconteceu?

Apos instalar o modulo de integracao PagBank ao Magento 2.4.6 e seguir para as configuracoes, ao solicitar "Authorize Store Default Config in Envirorment for Tests", login e senha feitos, clicar Autorizar na pagina do PagBank, estou sendo redirecionado a minha loja com a resposta "Unable to get the code...".

### Método de Instalação

Via Composer

### Versão da Magento/Adobe

2.4.6+ (Magento/Adobe >= 2.4.6)

### Qual a versão do PHP?

PHP 8.2

### Meu log não contém informações confidenciais

- [X] Não estou enviando dados que violem a privacidade do cliente ou da loja.

### Qual a gravidade do problema?

Não consegui configurar o modulo

**Comment by elisei** [comment]
Olá @ch31z3r83 

Você consegue testar com a autenticação em produção?

**Comment by ch31z3r83** [comment]
Ola Elisei! Obrigado pelo contato. Tentei configurar pela opcao em producao e obtive a mesma resposta. 

<img width="715" alt="pagbank_error" src="https://github.com/pagseguro/payment-magento/assets/81702472/12e3f5bf-edf3-4556-93f4-cf4191c61063">

**Comment by elisei** [comment]
@ch31z3r83 

Por favor post a saida do comando:
```
composer show pagbank/payment-magento --all
```

**Comment by ch31z3r83** [comment]
cheizer@piriadventure:~$ composer show pagbank/payment-magento --all
No composer.json found in the current directory, showing available packages from packagist.org
name     : pagbank/payment-magento
descrip. : PagBank - Payment for Magento and Adobe
keywords :
versions : 100.2.35, 100.2.34, 100.2.33, 100.2.32, 100.2.31-p2, 100.2.31-p1, 100.2.31, 100.2.30, 100.2.29, 100.2.28, 100.2.27, 100.2.26, 100.2.25, 100.2.24, 100.2.23, 100.2.22, 100.2.21, 100.2.20, 100.2.18, 100.2.17, 100.2.16, 100.2.15, 100.2.14, 100.2.10, 100.2.9, 100.2.8, 100.2.7, 100.2.5, 100.2.3, 100.2.2, 100.2.1, 100.1.35, 100.1.34, 100.1.33, 100.1.32, 100.1.31, 100.1.30, 100.1.29, 100.1.28, 100.1.27, 100.1.26, 100.1.24, 100.1.23, 100.1.22, 100.1.21, 100.1.20, 100.1.18, 100.1.16, 100.1.15, 100.1.14, 100.1.13, 100.1.12, 100.1.11, 100.1.10, 100.1.9, 100.1.8, 100.1.7, 100.1.6, 100.1.5, 100.1.4, 100.1.3, 100.1.2, 100.1.1, 100.0.35, 100.0.34, 100.0.33, 100.0.32, 100.0.31, 100.0.30, 100.0.29, 100.0.28, 100.0.27, 100.0.26, 100.0.25, 100.0.24, 100.0.23, 100.0.22, 100.0.21-p1, 100.0.21, 100.0.20-p1, 100.0.20, 100.0.18, 100.0.16, 100.0.14, 100.0.10, 100.0.9, 100.0.8, 100.0.7, 100.0.6, 100.0.3, 100.0.2, 100.0.1, dev-Magento@2.4.6, dev-Magento@2.4.0-2.4.5, dev-Magento@2.3.x
type     : magento2-module
license  : Open Software License 3.0 (OSL-3.0) (OSI approved) https://spdx.org/licenses/OSL-3.0.html#licenseText
license  : Academic Free License v3.0 (AFL-3.0) (OSI approved) https://spdx.org/licenses/AFL-3.0.html#licenseText
homepage :
source   : [git] https://github.com/pagseguro/payment-magento.git 8fa50611017b1ac6f59f23fcec2b4b1478dc7ca1
dist     : [zip] https://api.github.com/repos/pagseguro/payment-magento/zipball/8fa50611017b1ac6f59f23fcec2b4b1478dc7ca1 8fa50611017b1ac6f59f23fcec2b4b1478dc7ca1
names    : pagbank/payment-magento

support
issues : https://github.com/pagseguro/payment-magento/issues
source : https://github.com/pagseguro/payment-magento/tree/100.2.35

autoload
files
psr-4
PagBank\PaymentMagento\ => .

requires
php ~8.1.0||~8.2.0
magento/framework *
magento/module-customer *
magento/module-config *
magento/module-eav *
magento/module-sales *
magento/module-directory *
magento/module-checkout *
magento/module-backend *
magento/module-theme *
magento/module-ui *
magento/module-payment *
magento/module-vault *
ext-json *

requires (dev)
magento/magento-coding-standard *
phpmd/phpmd ^2.13
phpstan/extension-installer ^1.2
phpstan/phpstan ^1.6.8
phpunit/phpunit ^9.0

**Comment by elisei** [comment]
Olá @ch31z3r83,

Obrigado, por favor por esse não ser um problema comum vou precisar investigar diretamente no seu projeto, podemos marcar uma reunião para alinharmos isso?

Caso possa, por favor entre em contato comigo em: osw_belisei@pagseguro.com e me indique 3 horários.

**Comment by elisei** [comment]
Olá @ch31z3r83 

Estou fechando o issue baseado na informação que me enviou de que conseguiu realizar o login após inserir o SSL na loja!

**Comment by ch31z3r83** [comment]
Combinado e muito obrigado.

Cheizer

Em qui., 8 de fev. de 2024 às 13:19, Bruno ***@***.***>
escreveu:
