### ISSUE TITLE
[Bug]: HTTP ERROR 500 Painel Admin (Order)

### ISSUE THREAD

**Issue by mauricio-tonny** [pagseguro/payment-magento#56]
### Contact details

mauricio@plataformamagento.com.br

### What happened?

Após instalar e configurar o módulo, ao tentar abrir qualquer pedido retorna erro 500 (modo desenvolvimento ou produção), Magento 2.3.3, PHP 7.3, instalado via Composer

Testado na versão:
composer require pagbank/payment-magento:~100.0 e composer require pagbank/payment-magento:~100.0.34

### Magento version

2.3.x (Magento >= 2.3.0 e < 2.4.0)

### What version of php?

PHP 7.3

### Are there relevant logs about the problem?

```bash
No log não retorna nada relacionado.
```

### My log does not contain confidential information

- [X] I am not sending data that violates the privacy of the customer or the store.

### What is the severity of the problem?

The store was offline

**Comment by elisei** [comment]
Olá @mauricio-tonny tudo bem?

Por favor veja o arquivo /var/log/exception.log nele terá alguma informação útil para entendernos o que ocorre.

**Comment by mauricio-tonny** [comment]
Opa mestre @elisei nem ao menos gera log sobre o erro ou qualquer coisa relacionado ao módulo, chequei algumas vezes,

**Comment by elisei** [comment]
Tenta nos logs do /var/log/nginx (lá do root do SO mesmo).

**Comment by elisei** [comment]
@mauricio-tonny  se não conseguir achar o log, me indique 3 sugestões de horários no email: brunoelisei@o2ti.com para realizarmos uma chamada de video e assim tentar orienta-lo:

**Comment by elisei** [comment]
Problema resolvido com nova sub-versão.
